### ISSUE TITLE
请教opencv编译报错

### ISSUE THREAD

**Issue by Rashomon5487** [Martin20150405/SLAM_AR_Android#4]
../../../../src/main/cpp/src/ORBextractor.cc:1025: error: undefined reference to 'cv::KeyPointsFilter::retainBest(std::__ndk1::vector<cv::KeyPoint, std::__ndk1::allocator<cv::KeyPoint> >&, int)'

我在编译的时候遇到这个问题，请问该怎么解决

**Comment by Martin20150405** [comment]
> ../../../../src/main/cpp/src/ORBextractor.cc:1025: error: undefined reference to 'cv::KeyPointsFilter::retainBest(std::__ndk1::vector<cv::KeyPoint, std::__ndk1::allocatorcv::KeyPoint >&, int)'
> 
> 我在编译的时候遇到这个问题，请问该怎么解决

新版NDK的编译工具链与OpenCV 3.x的冲突导致的，OpenCV 3.x中的签名应该是std::vector，可以尝试最新的Commit，应该可以在最新版（2021.3）AS、Gradle、SDK、NDK版本下编译运行
